# GoReleaser configuration for Linux-only builds
#
# Copyright (c) 2025 Deep Thought Labs
# All rights reserved.
#
# This file is part of the Infinite Drive blockchain tooling.
#
# Purpose: Faster development builds limited to Linux platforms only
#          Targets: Linux AMD64 and Linux ARM64
#
# Usage:
#   - make release-dry-run-linux    # Quick test build for Linux platforms only
#
# Important Limitations:
#   - ⚠️  Linux ARM64 builds may FAIL when running on Mac M1 with Docker emulation
#      This is expected due to cross-compilation toolchain limitations in emulated Docker
#      ARM64 builds will work correctly in GitHub Actions (Ubuntu native environment)
#   - Linux AMD64 builds should work correctly in all environments
#   - Both .goreleaser.yml and this file now target only Linux (amd64, arm64)
#   - This configuration is primarily for faster local development testing
#   - Main .goreleaser.yml is used by GitHub Actions for production releases
#
# See: guides/BUILDING_AND_RELEASES.md for detailed documentation
#
version: 1
project_name: infinite

# Build configuration - Solo Linux
builds:
  # Build for Linux AMD64
  - id: infinited_amd64
    dir: infinited
    main: ./cmd/infinited
    binary: infinited
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=infinite
      - -X github.com/cosmos/cosmos-sdk/version.AppName=infinited
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cometbft/cometbft/version.TMCoreSemVer={{ .Env.TMVERSION }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo
    tags:
      - netgo
    targets:
      - linux_amd64

  # Build for Linux ARM64 with explicit cross-compiler
  - id: infinited_arm64
    dir: infinited
    main: ./cmd/infinited
    binary: infinited
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc  # Explicit cross-compiler for ARM64 CGO cross-compilation
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=infinite
      - -X github.com/cosmos/cosmos-sdk/version.AppName=infinited
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cometbft/cometbft/version.TMCoreSemVer={{ .Env.TMVERSION }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo
    tags:
      - netgo
    targets:
      - linux_arm64

# Archive configuration
archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: linux
        format: tar.gz
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
    wrap_in_directory: false

# Checksums configuration
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Snapshot configuration
snapshot:
  name_template: "{{ .Tag }}-next"

# Changelog configuration
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'Merge pull request'
      - 'Merge branch'

# Release configuration (para uso futuro)
release:
  github:
    owner: deep-thought-labs
    name: infinite
  header: |
    ## Infinite Drive {{ .Tag }}
    
    Release {{ .Tag }} de Infinite Drive (Linux builds only).
  footer: |
    ---
    
    **Full Changelog**: https://github.com/deep-thought-labs/infinite/compare/{{ .PreviousTag }}...{{ .Tag }}
  # Mode: auto creates release if doesn't exist, updates if exists (consistent with .goreleaser.yml)
  mode: auto

