name: Check Markdown links
on:
  pull_request:
    branches:
      - main
      - release/**
permissions: read-all

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      md: ${{ steps.filter.outputs.md }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            md:
              - '**/*.md'
              - '*.md'
              - 'mlc_config.json'
              - '.github/workflows/markdown-links.yml'

  markdown-link-check:
    needs: changes
    if: needs.changes.outputs.md == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@master
        with:
          check-modified-files-only: "yes"
          use-quiet-mode: "yes"
          base-branch: "main"
          config-file: "mlc_config.json"
