name: Slither Analysis

on:
  pull_request:
permissions: read-all

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      sol: ${{ steps.filter.outputs.sol }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            sol:
              - '**/*.sol'
              - '.github/workflows/slither.yml'

  analyze:
    name: Run Slither
    needs: changes
    if: needs.changes.outputs.sol == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Node dependencies Install
        run: |
          cd contracts && npm i
          cp -r node_modules/@openzeppelin .
      - name: Run Slither Action
        uses: crytic/slither-action@v0.4.0
        continue-on-error: true
        id: slither
        with:
          target: contracts/
